### ISSUE TITLE
关于skip_epoch

### ISSUE THREAD

**Issue by luuuyi** [anxiangsir/NAIC_reid_challenge_rank14_rank25#1]
你好，看到你代码里面有一个skip sampler，这个采样器会比strong baseline里面的默认采样器有什么优势么。在实际使用中。

**Comment by anxiangsir** [comment]
1. 我们采用了过采样（样本数小于100的id，多采样一倍），效果提升明显；
2. 比赛有时间要求，所以我们每隔几个epoch过采样一次，让训练和精度达到一个trade off;

**Comment by luuuyi** [comment]
@anxiangsir 好的，感谢
